-- Supabase Setup Script for Chamunda Jewellers
-- Run this in your Supabase SQL Editor to create the products table

-- 1. Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  collection TEXT,
  tags TEXT[],
  desc TEXT,
  image TEXT,
  images TEXT[],
  featured BOOLEAN DEFAULT FALSE,
  availability BOOLEAN DEFAULT TRUE,
  code TEXT UNIQUE
);

-- 2. Setup Row Level Security (RLS)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- 3. Create policies
-- Allow everyone to read products (for the website to display them)
CREATE POLICY "Allow public read access"
ON products FOR SELECT
USING (true);

-- Allow authenticated users to insert/update/delete products
CREATE POLICY "Allow authenticated full access"
ON products FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');

-- Note: In Supabase Dashboard, you also need to create a User in Auth > Users
-- so you can login with those credentials on the /admin page.
